pipeline {
  agent any

  stages {
      stage('start') {
        steps {
          echo "Start"
        }
      }
      stage('create') {
        steps {
          sh "mkdir -p devops"
        }
      }
      stage('end') {
        steps {
          echo "Completed"
        }
      }
  }
}
